import {
  userTermsAcceptanceAcknowledgements as PLATFORM_NOTICE_ACKNOWLEDGEMENTS,
  USER_TERMS_ACCEPTANCE_EFFECTIVE_DATE as PLATFORM_NOTICE_EFFECTIVE_DATE,
  USER_TERMS_ACCEPTANCE_LABEL as PLATFORM_NOTICE_ACKNOWLEDGEMENT_LABEL,
  userTermsAcceptanceParagraphs as PLATFORM_NOTICE_PARAGRAPHS,
  USER_TERMS_ACCEPTANCE_VERSION as PLATFORM_NOTICE_VERSION,
} from './userTerms';

export { PLATFORM_NOTICE_ACKNOWLEDGEMENTS, PLATFORM_NOTICE_EFFECTIVE_DATE, PLATFORM_NOTICE_ACKNOWLEDGEMENT_LABEL, PLATFORM_NOTICE_PARAGRAPHS, PLATFORM_NOTICE_VERSION };

export const PLATFORM_NOTICE_ERROR_MESSAGE = 'Please accept the Terms & Conditions For Users before continuing.';
